version: 2
jobs:
  build:
    working_directory: ~/pantheon-systems/wordpress-upstream
    parallelism: 1
    docker:
    - image: circleci/php:5.6
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dep-{{ .Branch }}-
        - v1-dep-master-
    - run: |
        sudo apt-get install -y libmcrypt-dev
        sudo docker-php-ext-install mcrypt
    - run: echo -e "[Date]\ndate.timezone = UTC" | sudo tee /usr/local/etc/php/php.ini > /dev/null
    - run: echo $(openssl rand -hex 8) > /tmp/WORDPRESS_ADMIN_PASSWORD
    - run: |
        echo 'export PATH=/tmp/terminus/bin:$PATH' >> $BASH_ENV
        echo 'export TERMINUS_ENV=ci-$CIRCLE_BUILD_NUM' >> $BASH_ENV
        echo 'export TERMINUS_SITE=wordpress-upstream' >> $BASH_ENV
        echo 'export SITE_ENV=wordpress-upstream.ci-$CIRCLE_BUILD_NUM' >> $BASH_ENV
        echo 'export WORDPRESS_ADMIN_USERNAME=pantheon' >> $BASH_ENV
        echo 'export WORDPRESS_ADMIN_EMAIL=no-reply@getpantheon.com' >> $BASH_ENV
        echo 'export WORDPRESS_ADMIN_PASSWORD=$(cat /tmp/WORDPRESS_ADMIN_PASSWORD)' >> $BASH_ENV
        source $BASH_ENV
    - run: echo "StrictHostKeyChecking no" >> "$HOME/.ssh/config"
    - run: |
        if [ -z "$GITHUB_TOKEN" ]; then
          echo "GITHUB_TOKEN environment variables missing; assuming unauthenticated build"
          exit 0
        fi
        echo "Setting GitHub OAuth token with suppressed ouput"
        {
          composer config -g github-oauth.github.com $GITHUB_TOKEN
        } &> /dev/null
    - run: |
        if [ -z "$TERMINUS_TOKEN" ]; then
          echo "TERMINUS_TOKEN environment variables missing; assuming unauthenticated build"
          exit 0
        fi
        composer install
        git clone --branch master https://github.com/pantheon-systems/terminus.git /tmp/terminus
        cd /tmp/terminus && composer install
        terminus auth:login --machine-token=$TERMINUS_TOKEN
    - save_cache:
        key: v1-dep-{{ .Branch }}-{{ epoch }}
        paths:
        - ~/.composer/cache
    - run: ./prepare.sh
    - run: ./test.sh --strict
    - run: ./cleanup.sh
